name: sass_builder
version: 0.0.1
description: Simple build wrapper around the new dart-sass package
dependencies:
  build: ^0.5.0
  sass:
    git: https://github.com/sass/dart-sass.git
dev_dependencies:
  test: